name = "engineering-studio"
main = ".open-next/worker-bundle/index.js"
pages_build_output_dir = ".open-next/output/client"
compatibility_date = "2024-04-05"

[placement]
mode = "smart"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "engineering-studio-r2"
preview_bucket_name = "engineering-studio-r2"

[[d1_databases]]
binding = "DB"
database_name = "engineering-studio-db"
database_id = "a8af5221-4f89-4835-acf9-268d00af3f8f"

[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "engineering-studio-vectors"

[ai]
binding = "AI"
